<?php
/**
 * @file
 * Code for the SCF Web Resource feature.
 */

include_once('scf_web_resource.features.inc');

define('SCF_WEB_RESOURCE_NODE_TYPE', 'web_resource');

/**
 * Implements hook_form()
*/
function scf_web_resource_menu() {
  //Import Component for SCF Collections
  $items['node/%node/web_resource_import'] = array(
    'title' => 'Web Resource Import',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scf_web_resource_import_form'),
    'file' => 'scf_web_resource.import.inc',
    'access callback' => 'scf_web_resource_local_task_loader',
    'access arguments' => array(1),
    'weight' => 8,
  );

  return $items;
}

function scf_web_resource_admin_paths() {
  $paths = array( 
    'node/*/web_resource_import' => TRUE,
  );
  return $paths;
}

function scf_web_resource_local_task_loader($node) {
  global $user;

  //Check node access perms
  $access_granted = node_access('update', $node);

  if($node->type == SCFC_TOPIC_QUEUE_TYPE && $access_granted) {
    return TRUE;
  }
  else {
    return FALSE;
  } 
}

/**
 * Hook for saving a Web Resource by URL.
 * Attempts to import Title and Description from remote resource 
 * @param $url
 *   Remote URL to import
 * @return $nid
 *   Returns nid of saved web resource
*/
function scf_web_resource_import_by_url($url) {
  global $user;
  require_once('includes/phpQuery-onefile.php');
  $request = drupal_http_request($url);
  $node = new stdClass();
  if($request->code == '200' && !empty($request->data)) {
    $document = phpQuery::newDocumentHTML($request->data);
    $title = $document->find('title')->text();
    $description = $document->find('meta[name="description"]')->attr('content');
    //Create the web resource node object
    $node->type = SCF_WEB_RESOURCE_NODE_TYPE;
    node_object_prepare($node);
    $node->language = LANGUAGE_NONE;
    $node->title = $title;
    $node->field_url[LANGUAGE_NONE][0]['url'] = $url;
    $node->body[LANGUAGE_NONE][0]['value'] = $description;
    $node->uid = $user->uid;
    $node->status = 0;
    $result = node_save($node);
    return !empty($node->nid) ? $node->nid : false;
  }
  return false;
}
