<?php

/**
 * Implements hook_form()
*/
function journalstream_bookmarklet_menu() {
  $items['journalstream/bookmarklet/proxy'] = array( 
    'title' => 'Proxy1',
    'page callback' => 'journalstream_bookmarklet_portal_proxy',
    'type' => MENU_CALLBACK,
    'file' => 'journalstream_bookmarklet.proxy.inc',
    'access callback' => 'user_access',
    'access arguments' => array('access content') 
  );
  $items['node/%node/bookmarklet'] = array(
    'title' => 'Bookmarklet',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('journalstream_bookmarklet_view'),
    'access callback' => 'journalstream_web_resource_local_task_loader',
    'access arguments' => array(1),
    'weight' => 9,
  );
  //Bookmarklet Handler for Topic Queues
  $items['node/%node/bookmarklet_handler'] = array( 
    'title' => 'Web Resources Bookmarklet Handler',
    'type' => MENU_CALLBACK,
    'page callback' => 'journalstream_bookmarklet_handler',
    'file' => 'journalstream_bookmarklet.handler.inc',
    'access callback' => 'user_access',
    'access arguments' => array('access content'), 
  );
  // Bookmarklet handler for redirected requests
  $items['node/%node/bookmarklet_redirect_handler'] = array( 
    'title' => 'Web Resources Bookmarklet Redirect Handler',
    'type' => MENU_CALLBACK,
    'page callback' => 'journalstream_bookmarklet_redirect_handler',
    'file' => 'journalstream_bookmarklet.handler.inc',
    'access callback' => 'journalstream_web_resource_local_task_loader',
    'access arguments' => array(1), 
  ); 
  return $items;
}

function journalstream_bookmarklet_view() {
  $node = menu_get_object();
  $form = array();
  $form['bookmarklet'] = array( 
    '#type' => 'markup',
    '#markup' => _journalstream_bookmarklet_get_bookmarklet_js($node->nid),
  );
  $form['description'] = array( 
    '#type' => 'markup',
    '#markup' =>  '<p>' . t('Drag the link above to your browsers toolbar. It will create a bookmarklet for this topic queue') . '</p>', 
  );
  return $form;
}

/**
 * Helper function for generating bookmarklet javascript
*/
function _journalstream_bookmarklet_get_bookmarklet_js($nid) {
  global $base_url;
  $module_path = drupal_get_path('module', 'journalstream_bookmarklet');
  $porthole_path = $base_url . '/' . $module_path . '/javascripts/porthole.js';
  $bookmarklet_path = $base_url . '/' . $module_path . '/webresource.js';
  $form_action = $base_url . '/node/' . $nid . '/bookmarklet_handler';
  $login_url = $base_url . '/user?destination=node/' . $nid . '/bookmarklet_redirect_handler' ;
  $proxy_url = $base_url . '/journalstream/bookmarklet/proxy';
  $params = "{ 
    form_action: '$form_action',
    login_url: '$login_url',
    proxy_url: '$proxy_url'
  }";
  $jsfunction = <<<EOF
function bookmark() {
 var d = document,
 s1 = d.createElement('scr' + 'ipt'),
 s2 = d.createElement('scr' + 'ipt'),
 b = d.body,
 l = d.location;
 try {
   if (!b) throw (0);
   d.title = '(Saving...) ' + d.title;
   s1.setAttribute('src', '%s' + '?t=' + (new Date().getTime()));
   s2.setAttribute('src', '%s' + '?t=' + (new Date().getTime()));
   if(typeof(WebResource) == 'undefined') {
     b.appendChild(s1);
     b.appendChild(s2);
   }
 } catch(e) {
   alert('Please wait until the page has loaded.');
 }
}
function run() {
  var webresource = new WebResource; 
  var params = %s; 
  webresource.init(params); 
}
 bookmark();
 setTimeout(function() {run();},1000);
 void(0)
EOF;
  $js = sprintf($jsfunction, $porthole_path, $bookmarklet_path, $params);
  $js = preg_replace("/\n|\t|\s{2}/",'',$js);
  $output = '<a href="javascript:' . $js . '" title="Add to Queue">Add to Queue</a>';
  return $output;
}
